[postgres]
enabled = true
origin_host = "localhost"
origin_user = "postgres"
origin_password = "password"
origin_port = "5432"
origin_database = "postgres"

target_host = "localhost"
target_user = "postgres"
target_password = "password"
target_port = "5433"
target_database = "postgres"

[smtp]
enabled = false

username = "example@example.com"
password = "secretpass"

smtp_host = "posteo.de"
smtp_port = 587

from = "example@example.com"
to = [ "example@example.com", "example@example.com" ]
cc = [ "example@example.com" ]
