name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test

    - name: Install cargo-deb
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-deb
    - name: Package debian
      run: cargo deb --no-strip --verbose
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: debian-package
        path: target/debian/cnc-rs*.deb
